const networks = {
  BTC: ['Bitcoin'], ETH: ['Ethereum'], USDT: ['Ethereum (ERC20)', 'TRON (TRC20)', 'BNB Smart Chain (BEP20)'], SOL: ['Solana'], BNB: ['BNB Smart Chain'], ADA: ['Cardano'], DOGE: ['Dogecoin'], XRP: ['XRP Ledger'], TRX: ['TRON'], LTC: ['Litecoin']
};
const targets = { BTC:6, ETH:12, USDT:12, SOL:12, BNB:12, ADA:20, DOGE:6, XRP:1, TRX:20, LTC:6 };
const $ = (id) => document.getElementById(id);
const coin = $('coin-select'), chain = $('chain-select'), form = $('tracker-form'), button = form.querySelector('button');
function updateChains(){ chain.innerHTML = (networks[coin.value] || []).map(n => `<option>${n}</option>`).join(''); }
function explorer(c,n,h){ const x=String(n).toLowerCase(); const urls={BTC:`https://www.blockchain.com/btc/tx/${h}`,ETH:`https://etherscan.io/tx/${h}`,USDT:x.includes('tron')?`https://tronscan.org/#/transaction/${h}`:x.includes('bep')?`https://bscscan.com/tx/${h}`:`https://etherscan.io/tx/${h}`,SOL:`https://solscan.io/tx/${h}`,BNB:`https://bscscan.com/tx/${h}`,ADA:`https://cardanoscan.io/transaction/${h}`,DOGE:`https://dogechain.info/tx/${h}`,XRP:`https://xrpscan.com/tx/${h}`,TRX:`https://tronscan.org/#/transaction/${h}`,LTC:`https://blockchair.com/litecoin/transaction/${h}`}; return urls[c] || '#'; }
async function json(url, options={}){ const r=await fetch(url,{headers:{Accept:'application/json'},...options}); if(!r.ok) throw Error(`API ${r.status}`); return r.json(); }
function render(r,c,n,h){ const p=Math.max(0,Math.min(100,r.progress||0)); $('transaction-status').textContent=r.status; $('status-pill').textContent=r.status; $('status-pill').className=`status-pill ${r.status.toLowerCase()}`; $('progress-text').textContent=`${Math.round(p)}%`; $('progress-bar').style.width=`${p}%`; $('confirmations').textContent=r.confirmations ?? 0; $('network-name').textContent=r.network||n; $('target-confirmations').textContent=r.target||targets[c]; $('block-height').textContent=r.block||'-'; $('tx-hash-display').textContent=h; $('explorer-link').href=explorer(c,n,h); $('explorer-link').textContent='Open explorer'; $('last-update').textContent=new Date().toLocaleTimeString(); }
async function btc(h){ const [t,height]=await Promise.all([json(`https://mempool.space/api/tx/${h}`),json('https://mempool.space/api/blocks/tip/height')]); const ok=!!t.status?.confirmed, conf=ok?Math.max(0,Number(height)-Number(t.status.block_height)+1):0; return {status:ok?'Confirmed':'Pending',confirmations:conf,target:6,block:ok?t.status.block_height:'-',network:'Bitcoin',progress:Math.min(conf/6*100,100)}; }
async function blockscout(h,network,c){ const t=await json(`https://eth.blockscout.com/api/v2/transactions/${h}`); const conf=Number(t.confirmations||t.confirmation_count||0); return {status:conf?'Confirmed':'Pending',confirmations:conf,target:targets[c],block:t.block_number||'-',network,progress:Math.min(conf/targets[c]*100,100)}; }
async function bsc(h){ const t=await json(`https://bsc.blockscout.com/api/v2/transactions/${h}`); const conf=Number(t.confirmations||t.confirmation_count||0); return {status:conf?'Confirmed':'Pending',confirmations:conf,target:12,block:t.block_number||'-',network:'BNB Smart Chain',progress:Math.min(conf/12*100,100)}; }
async function sol(h){ const post={method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getTransaction',params:[h,{encoding:'jsonParsed',maxSupportedTransactionVersion:0}]})}; const t=(await fetch('https://api.mainnet-beta.solana.com',post)).json?await (await fetch('https://api.mainnet-beta.solana.com',post)).json():null; if(!t?.result)return {status:'Pending',confirmations:0,target:12,network:'Solana',block:'-',progress:0}; return {status:'Confirmed',confirmations:1,target:12,network:'Solana',block:`Slot ${t.result.slot||'-'}`,progress:8.33}; }
async function tron(h){ const t=await json(`https://apilist.tronscanapi.com/api/transaction-info?hash=${encodeURIComponent(h)}`); const conf=Number(t.confirmations||0); return {status:conf?'Confirmed':'Pending',confirmations:conf,target:20,network:'TRON',block:t.blockNumber||'-',progress:Math.min(conf/20*100,100)}; }
async function xrp(h){ const t=await json(`https://data.ripple.com/v2/transactions/${encodeURIComponent(h)}`); const ok=t.validated===true&&(!t.outcome||t.outcome.result==='tesSUCCESS'); return {status:ok?'Confirmed':'Pending',confirmations:ok?1:0,target:1,network:'XRP Ledger',block:t.ledger_index||'-',progress:ok?100:0}; }
async function query(c,n,h){ const l=n.toLowerCase(); if(c==='BTC')return btc(h); if(c==='ETH')return blockscout(h,'Ethereum',c); if(c==='USDT')return l.includes('tron')?tron(h):l.includes('bep')?bsc(h):blockscout(h,'Ethereum (ERC20)',c); if(c==='BNB')return bsc(h); if(c==='SOL')return sol(h); if(c==='TRX')return tron(h); if(c==='XRP')return xrp(h); throw Error('This network is not available yet'); }
coin.addEventListener('change',updateChains); updateChains();
form.addEventListener('submit',async e=>{ e.preventDefault(); const c=coin.value,n=chain.value,h=$('tx-hash').value.trim(); if(!h)return; button.disabled=true; button.textContent='Checking…'; render({status:'Pending',progress:0,confirmations:0,target:targets[c],network:n,block:'-'},c,n,h); try{ render(await query(c,n,h),c,n,h); }catch(err){ console.error(err); render({status:'Failed',progress:0,confirmations:0,target:targets[c],network:n,block:'-'},c,n,h); }finally{button.disabled=false;button.textContent='Check transaction';} });
